# Setup
title:        Trivedi Research Group
tagline:      
baseurl:      ""
paginate:     4
locale:       "en"

# About/contact
author:
  name:       Dhara Trivedi
  email:      dtrivedi@clarkson.edu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
social:
  - name: Twitter
    icon: twitter
    username: TrivediLab
    url: https://twitter.com/djtrivedi
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: dharatrivedi
    url: https://github.com/dharatrivedi
    desc: Fork me on GitHub
    share: true
