theme: jekyll-theme-cayman
# Setup
title:        Trivedi Research Group
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

<section class="page-header">
  <h1 class="project-name">{{ site.title }}</h1>
  <h2 class="project-tagline">{{ site.tagline }}</h2>
  <a href="#" class="btn">View on GitHub</a>
  <a href="#" class="btn">Download .zip</a>
  <a href="#" class="btn">Download .tar.gz</a>
</section>
