# Setup
title:        Trivedi Research Group
tagline:      
baseurl:      ""
paginate:     4
locale:       "en"

# About/contact
author:
  name:       Dhara Trivedi
  email:      dtrivedi@clarkson.edu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
social:
  - name: Twitter
    icon: twitter
    username: TrivediLab
    url: https://twitter.com/djtrivedi
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: dharatrivedi
    url: https://github.com/dharatrivedi
    desc: Fork me on GitHub
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
