theme: jekyll-theme-cayman
# Setup
title:        Trivedi Research Group
tagline:      
baseurl:      ""
paginate:     1
locale:       "en"

<a href="#" class="btn">View on GitHub</a>
  <a href="#" class="btn">Download .zip</a>
  <a href="#" class="btn">Download .tar.gz</a>
  
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
